# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 02:36
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T', models.DateField()),
                ('Symbol', models.CharField(help_text='Symbol', max_length=10)),
                ('Featuredata', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturesMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField(blank=True, help_text='User ID from database', null=True)),
                ('Featurelabel', models.CharField(help_text='unique label', max_length=50, unique=True)),
                ('Featuredescription', models.CharField(blank=True, help_text='Company name', max_length=100, null=True)),
                ('Category', models.CharField(blank=True, help_text='Company name', max_length=100, null=True)),
                ('Returntype', models.CharField(blank=True, help_text='Company name', max_length=100, null=True)),
                ('operators', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, size=None)),
                ('Query', models.BooleanField(default=True, help_text='Update data for this Symbol')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
