# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featureapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuresmeta',
            name='UserID',
        ),
        migrations.AddField(
            model_name='featuresmeta',
            name='Userfilename',
            field=models.CharField(blank=True, help_text='User ID from database', max_length=150),
        ),
        migrations.AlterField(
            model_name='featuresmeta',
            name='Query',
            field=models.BooleanField(default=True, help_text='Use it in query'),
        ),
    ]
