# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-15 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('featureapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuresmeta',
            name='FeatureCode',
        ),
        migrations.DeleteModel(
            name='FeatureComputeCode',
        ),
    ]
