# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featureapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurecomputecode',
            name='Code',
            field=models.TextField(help_text=b'Code of all the features', null=True),
        ),
        migrations.AlterField(
            model_name='featurecomputecode',
            name='File',
            field=models.FilePathField(help_text=b'File of all the features', null=True),
        ),
    ]
