# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-09 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('featureapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuresmeta',
            name='Userfilename',
        ),
        migrations.AddField(
            model_name='featuresmeta',
            name='FeatureCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='featureapp.FeatureComputeCode'),
        ),
    ]
