# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 04:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('featureapp', '0002_auto_20170515_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuresdata',
            name='Featuredata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
