# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featureapp', '0002_auto_20170516_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurecomputecode',
            name='File',
            field=models.FilePathField(help_text=b'File of all the features', max_length=400, null=True),
        ),
    ]
