# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-01 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Starttime', models.DateTimeField()),
                ('Endtime', models.DateTimeField()),
                ('Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
