# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-01 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ComputeSession_id', models.IntegerField(db_index=True, null=True)),
                ('ComputeStatus', models.CharField(choices=[('Fail', 'Fail'), ('ToDo', 'ToDo'), ('Success', 'Success'), ('Running', 'Running')], max_length=30, null=True)),
                ('Msg', models.TextField(blank=True, null=True)),
                ('ComputeStarttime', models.DateTimeField(null=True)),
                ('ComputeEndtime', models.DateTimeField(null=True)),
            ],
        ),
    ]
