# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-15 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computeapp', '0002_computestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computesession',
            name='Endtime',
            field=models.DateTimeField(null=True),
        ),
    ]
