# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 00:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeStatus_Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('ToDo', 'ToDo'), ('Run', 'Run'), ('Fail', 'Fail'), ('Success', 'Success')], max_length=10)),
                ('Symbol', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('Symbol_id', models.IntegerField(db_index=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryComputeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.TextField(help_text=b'Code of all the features', null=True)),
                ('File', models.FilePathField(help_text=b'File of all the features', max_length=400, null=True)),
                ('Username', models.CharField(blank=True, help_text=b'User ID from database', max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QueryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T', models.DateField()),
                ('Symbol', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('Symbol_id', models.IntegerField(db_index=True, null=True)),
                ('Querydata', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Userfilename', models.CharField(blank=True, help_text='User ID from database', max_length=150)),
                ('Querylabel', models.CharField(help_text='unique label', max_length=50, unique=True)),
                ('Querydescription', models.CharField(blank=True, help_text='Company name', max_length=100, null=True)),
                ('Category', models.CharField(blank=True, help_text='Company name', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
