# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 02:50
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockapp', '0013_auto_20170509_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryComputeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.TextField(help_text=b'Code of all the features', null=True)),
                ('File', models.FilePathField(help_text=b'File of all the features', max_length=400, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QueryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T', models.DateField()),
                ('Querydata', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.Stockmeta')),
            ],
        ),
        migrations.CreateModel(
            name='QueryMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Userfilename', models.CharField(blank=True, help_text='User ID from database', max_length=150)),
                ('Querylabel', models.CharField(help_text='unique label', max_length=50, unique=True)),
                ('Querydescription', models.CharField(blank=True, help_text='Company name', max_length=100, null=True)),
                ('Category', models.CharField(blank=True, help_text='Company name', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
