# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-15 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComputeStatus_Query',
        ),
        migrations.DeleteModel(
            name='QueryComputeCode',
        ),
    ]
