#!/bin/sh
##SBATCH --partition=debug
#SBATCH --partition=general-compute
##SBATCH --constraint=CPU-E5645
##SBATCH --partition=psingla
##SBATCH --clusters=mae
#SBATCH --time=20:00:00
#SBATCH --mem=10000
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --job-name="CorrCat"
#SBATCH --output=CorrCat.out
#SBATCH --mail-user=nagavenk@buffalo.edu
#SBATCH --mail-type=ALL
##SBATCH --requeue
#Specifies that the job will be requeued after a node failure.
#The default is that the job will not be requeued.

echo "SLURM_JOB_ID="$SLURM_JOB_ID
echo "SLURM_JOB_NODELIST"=$SLURM_JOB_NODELIST
echo "SLURM_NNODES"=$SLURM_NNODES
echo "SLURMTMPDIR="$SLURMTMPDIR

echo "working directory = "$SLURM_SUBMIT_DIR

##module load python/anaconda
##module use /user/cdc/privatemodules
module use ~/privatemodules
module load anaconda_nagavenk
module load mpi4py
module list
ulimit -s unlimited
#
# Set IB Fabric to prevent stalling on large jobs
MY_IB=`ibstat -l`
echo "Found IB interface =" $MY_IB
if test $MY_IB == "qib0"
then
export I_MPI_FABRICS_LIST="tmi,dapl,tcp"
else if test $MY_IB == "mlx4_0"
then
export I_MPI_FABRICS_LIST="ofa,dapl,tcp"
else
export I_MPI_FABRICS_LIST="dapl,tcp"
fi
fi
echo "I_MPI_FABRICS_LIST="$I_MPI_FABRICS_LIST 
#
#export I_MPI_DEBUG=5
echo "Launch FeatureLinDocGen with srun"
NPROCS=`srun --nodes=${SLURM_NNODES} bash -c 'hostname' |wc -l`
echo "NPROCS="$NPROCS
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
srun python Maintainer.py

#
echo "All Done!"
