# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 00:54
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupName', models.CharField(max_length=200)),
                ('Misc', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('tag', models.CharField(max_length=200)),
                ('Modeltype', models.CharField(choices=[('Classification', 'Classification'), ('Regression', 'Regression')], max_length=20)),
                ('Datatype', models.CharField(choices=[('Raw', 'Raw'), ('RawProcessed', 'RawProcessed'), ('Derived', 'Derived'), ('Train', 'Train'), ('Validation', 'Validation'), ('Test', 'Test')], max_length=20)),
                ('Dataformat', models.CharField(choices=[('npz', 'npz'), ('h5', 'h5'), ('pkl', 'pkl'), ('joblib', 'joblib')], max_length=30)),
                ('Datashards', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('ShardInfo', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ParentData', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datascience.Data')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('Symbol', models.CharField(max_length=100)),
                ('T', models.DateField(null=True)),
                ('window', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MLmodels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('Misc', django.contrib.postgres.fields.jsonb.JSONField()),
                ('Status', models.CharField(choices=[('Trained', 'Trained'), ('UnTrained', 'UnTrained')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datascience.Data')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Misc', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mlmodels',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datascience.Project'),
        ),
        migrations.AddField(
            model_name='data',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datascience.Project'),
        ),
    ]
