# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 19:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datascience', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('Datatype', models.CharField(choices=[('Raw', 'Raw'), ('Derived', 'Derived'), ('Train', 'Train'), ('Validation', 'Validation'), ('Test', 'Test')], max_length=20)),
                ('Dataformat', models.CharField(choices=[('npz', 'npz'), ('dataFrame', 'dataFrame'), ('pkl', 'pkl')], max_length=30)),
                ('Datashards', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ParentData', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datascience.Data')),
            ],
        ),
        migrations.CreateModel(
            name='MLmodels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('Info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('Data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datascience.Data')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mlmodels',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datascience.Project'),
        ),
        migrations.AddField(
            model_name='data',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datascience.Project'),
        ),
    ]
