# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 03:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datascience', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Metrics', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='Datashards',
        ),
        migrations.AddField(
            model_name='data',
            name='ouput_type',
            field=models.CharField(choices=[('npz', 'npz'), ('h5', 'h5'), ('pkl', 'pkl'), ('joblib', 'joblib'), ('json', 'json')], default='binary', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlmodels',
            name='saveformat',
            field=models.CharField(choices=[('npz', 'npz'), ('h5', 'h5'), ('pkl', 'pkl'), ('joblib', 'joblib'), ('xgboost', 'xgboost'), ('keras', 'keras')], default='joblib', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='Dataformat',
            field=models.CharField(choices=[('npz', 'npz'), ('h5', 'h5'), ('pkl', 'pkl'), ('joblib', 'joblib'), ('json', 'json')], max_length=30),
        ),
        migrations.AlterField(
            model_name='mlmodels',
            name='Misc',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='mlmodels',
            name='Status',
            field=models.CharField(choices=[('Validated', 'Validated'), ('Trained', 'Trained'), ('UnTrained', 'UnTrained')], max_length=30),
        ),
        migrations.AddField(
            model_name='modelmetrics',
            name='Data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datascience.Data'),
        ),
        migrations.AddField(
            model_name='modelmetrics',
            name='MLmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datascience.MLmodels'),
        ),
    ]
