# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-24 04:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascience', '0002_auto_20170603_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeFunc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Group', models.CharField(max_length=200, null=True)),
                ('RequiredImports', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('Info', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('PklCode', models.TextField()),
                ('SrcCode', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Misc',
            new_name='Info',
        ),
        migrations.RenameField(
            model_name='mlmodels',
            old_name='Misc',
            new_name='Info',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Misc',
            new_name='Info',
        ),
        migrations.AddField(
            model_name='modelmetrics',
            name='Info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='data',
            name='Datatype',
            field=models.CharField(choices=[('Raw', 'Raw'), ('RawProcessed', 'RawProcessed'), ('Train', 'Train'), ('Validation', 'Validation'), ('Test', 'Test')], max_length=20),
        ),
    ]
