# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascience', '0004_auto_20170713_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computefunc',
            name='PklCode',
            field=models.BinaryField(),
        ),
    ]
