# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 05:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datascience', '0005_auto_20170714_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='computefunc',
            name='RequiredGroup',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
