# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-18 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datascience', '0007_auto_20170715_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodels',
            name='Data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datascience.Data'),
        ),
        migrations.AlterField(
            model_name='mlmodels',
            name='Project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datascience.Project'),
        ),
    ]
