# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 20:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datascience', '0008_auto_20170717_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, null=True),
        ),
    ]
