# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascience', '0010_data_datastructure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Datatype',
            field=models.CharField(choices=[('Raw', 'Raw'), ('Base', 'Base'), ('RawProcessed', 'RawProcessed'), ('Train', 'Train'), ('Validation', 'Validation'), ('Test', 'Test')], max_length=20),
        ),
    ]
