# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascience', '0011_auto_20170801_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='computefunc',
            name='Userfilename',
            field=models.CharField(blank=True, help_text='User Name from database', max_length=150),
        ),
        migrations.AlterField(
            model_name='data',
            name='ouput_type',
            field=models.CharField(choices=[('npz', 'npz'), ('h5', 'h5'), ('pkl', 'pkl'), ('joblib', 'joblib'), ('json', 'json')], default='binary', max_length=30),
        ),
    ]
