# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-09 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datascience', '0015_auto_20170804_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodels',
            name='Userfilename',
        ),
        migrations.AddField(
            model_name='mlmodels',
            name='Deploy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mlmodels',
            name='ModelCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='datascience.ModelCode'),
        ),
    ]
