# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmeta',
            name='Company',
            field=models.CharField(blank=True, help_text='Company name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockmeta',
            name='Competitors',
            field=models.CharField(blank=True, help_text='List of Competitors', max_length=1100, null=True),
        ),
        migrations.AlterField(
            model_name='stockmeta',
            name='Industry',
            field=models.CharField(blank=True, db_index=True, help_text='Stock Industry', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockmeta',
            name='LastPriceUpdate',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockmeta',
            name='Marketcap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Market Capitalization', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockmeta',
            name='Sector',
            field=models.CharField(blank=True, db_index=True, help_text='Stock Sector', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockmeta',
            name='Status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_index=True, help_text='Active or not', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='stockmeta',
            name='Symbol',
            field=models.CharField(blank=True, db_index=True, default='SYMBOL', help_text='Stock Symbol', max_length=6),
        ),
    ]
