# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 05:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockapp', '0003_auto_20170501_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IndexCode', models.TextField(help_text='Code to compute the index')),
                ('IndexName', models.CharField(help_text='Name of the index', max_length=50)),
                ('IndexDescription', models.CharField(help_text='Description of the index', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('User', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='stockgroup',
            old_name='Watchlist_description',
            new_name='GroupDescription',
        ),
        migrations.RenameField(
            model_name='stockgroup',
            old_name='Watchlist_name',
            new_name='GroupName',
        ),
        migrations.AddField(
            model_name='stockmeta',
            name='DownloadData',
            field=models.BooleanField(default=True, help_text='Download data for this Symbol'),
        ),
        migrations.AddField(
            model_name='stockmeta',
            name='Lastdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='stockmeta',
            name='Startdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stockmeta',
            name='Labels',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ETF', 'ETF'), ('Stock', 'Stock'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Oil', 'Oil'), ('Inverse', 'Inverse'), ('Copper', 'Copper'), ('Entertainment', 'Entertainment'), ('Uranium', 'Uranium'), ('Coal', 'Coal'), ('Index', 'Index'), ('GroupIndex', 'GroupIndex')], max_length=84),
        ),
        migrations.AddField(
            model_name='stockgroup',
            name='Indicies',
            field=models.ManyToManyField(to='stockapp.IndexFunction'),
        ),
    ]
