# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0004_auto_20170501_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeStatus_Stockmeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('ToDo', 'ToDo'), ('Run', 'Run'), ('Fail', 'Fail'), ('Success', 'Success')], max_length=10)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('Symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.Stockmeta')),
            ],
        ),
    ]
