# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 03:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockapp', '0005_computestatus_stockmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IndexName', models.CharField(help_text='Name of the index', max_length=50)),
                ('IndexDescription', models.CharField(help_text='Description of the index', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.TextField(help_text='Code of all the indices')),
                ('File', models.FilePathField(help_text='File of all the indices')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='ComputeStatus_Stockmeta',
            new_name='ComputeStatus_Stockdownload',
        ),
        migrations.RemoveField(
            model_name='indexfunction',
            name='User',
        ),
        migrations.RenameField(
            model_name='stockmeta',
            old_name='DownloadData',
            new_name='Download',
        ),
        migrations.RemoveField(
            model_name='stockgroup',
            name='Indicies',
        ),
        migrations.AddField(
            model_name='stockmeta',
            name='ComputeFeature',
            field=models.BooleanField(default=True, help_text='Compute Features for this Symbol'),
        ),
        migrations.AddField(
            model_name='stockmeta',
            name='Derived',
            field=models.BooleanField(default=False, help_text='Download data for this Symbol'),
        ),
        migrations.AddField(
            model_name='stockmeta',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='stockgroup',
            name='User',
        ),
        migrations.AddField(
            model_name='stockgroup',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockmeta',
            name='Symbol',
            field=models.CharField(blank=True, db_index=True, default='SYMBOL', help_text='Stock Symbol', max_length=10),
        ),
        migrations.DeleteModel(
            name='IndexFunction',
        ),
        migrations.AddField(
            model_name='indexclass',
            name='IndexCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.IndexCode'),
        ),
        migrations.AddField(
            model_name='stockgroup',
            name='IndexClasses',
            field=models.ManyToManyField(to='stockapp.IndexClass'),
        ),
    ]
