# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 06:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0006_auto_20170504_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IndexName', models.CharField(blank=True, help_text='Name of the index', max_length=150, null=True)),
                ('IndexDescription', models.CharField(blank=True, help_text='Description of the index', max_length=500, null=True)),
                ('IndexLabel', models.CharField(help_text='Description of the index', max_length=50, unique=True)),
                ('IndexResultType', models.CharField(blank=True, help_text='Description of the index', max_length=20, null=True)),
                ('computefeatures', models.BooleanField(default=True, help_text='Run feature extractions on this index')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='indexclass',
            old_name='IndexName',
            new_name='ClassName',
        ),
        migrations.RemoveField(
            model_name='indexclass',
            name='IndexDescription',
        ),
        migrations.AddField(
            model_name='indexclass',
            name='ClassDescription',
            field=models.CharField(help_text='Description of the index', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='indexcode',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockgroup',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='index',
            name='IndexClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.IndexClass'),
        ),
    ]
