# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0007_auto_20170505_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockGroupIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.Index')),
            ],
        ),
        migrations.RemoveField(
            model_name='stockgroup',
            name='IndexClasses',
        ),
        migrations.AddField(
            model_name='computestatus_stockdownload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='stockgroupindex',
            name='StockGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.StockGroup'),
        ),
        migrations.AddField(
            model_name='stockgroupindex',
            name='Symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.Stockmeta'),
        ),
    ]
