# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0008_auto_20170505_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeStatus_StockGroupIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('ToDo', 'ToDo'), ('Run', 'Run'), ('Fail', 'Fail'), ('Success', 'Success')], max_length=10)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('StockGroupIndex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.StockGroupIndex')),
            ],
        ),
        migrations.RenameModel(
            old_name='IndexClass',
            new_name='IndexComputeClass',
        ),
        migrations.RenameModel(
            old_name='IndexCode',
            new_name='IndexComputeCode',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='IndexClass',
            new_name='IndexComputeClass',
        ),
        migrations.RenameField(
            model_name='indexcomputeclass',
            old_name='IndexCode',
            new_name='IndexComputeCode',
        ),
        migrations.AlterField(
            model_name='index',
            name='IndexLabel',
            field=models.CharField(help_text='Unique Abbreviated label for index', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='IndexName',
            field=models.CharField(blank=True, help_text='Long name', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='stockmeta',
            name='Symbol',
            field=models.CharField(blank=True, db_index=True, default='SYMBOL', help_text='Stock Symbol', max_length=10, unique=True),
        ),
    ]
