# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0009_auto_20170506_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computestatus_stockgroupindex',
            name='StockGroupIndex',
        ),
        migrations.DeleteModel(
            name='ComputeStatus_StockGroupIndex',
        ),
    ]
