# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0010_auto_20170506_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmeta',
            name='Download',
        ),
        migrations.AddField(
            model_name='stockmeta',
            name='Update',
            field=models.BooleanField(default=True, help_text='Update data for this Symbol'),
        ),
    ]
