# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0011_auto_20170506_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='IndexResultType',
            field=models.CharField(blank=True, help_text='Description of the index', max_length=100, null=True),
        ),
    ]
