# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-15 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0014_industry_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computestatus_stockdownload',
            name='Symbol',
        ),
        migrations.RemoveField(
            model_name='index',
            name='IndexComputeClass',
        ),
        migrations.RemoveField(
            model_name='indexcomputeclass',
            name='IndexComputeCode',
        ),
        migrations.RemoveField(
            model_name='indexcomputecode',
            name='User',
        ),
        migrations.RemoveField(
            model_name='stockgroupindex',
            name='Index',
        ),
        migrations.RemoveField(
            model_name='stockgroupindex',
            name='StockGroup',
        ),
        migrations.RemoveField(
            model_name='stockgroupindex',
            name='Symbol',
        ),
        migrations.RemoveField(
            model_name='stockmeta',
            name='ComputeFeature',
        ),
        migrations.RemoveField(
            model_name='stockmeta',
            name='User',
        ),
        migrations.AlterField(
            model_name='stockmeta',
            name='Derived',
            field=models.BooleanField(default=False, help_text='Is this derived from other stock prices'),
        ),
        migrations.DeleteModel(
            name='ComputeStatus_Stockdownload',
        ),
        migrations.DeleteModel(
            name='Index',
        ),
        migrations.DeleteModel(
            name='IndexComputeClass',
        ),
        migrations.DeleteModel(
            name='IndexComputeCode',
        ),
        migrations.DeleteModel(
            name='StockGroupIndex',
        ),
    ]
