# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stockprice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Close', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=9, null=True)),
                ('Open', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('High', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('Low', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('Volume', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('Date', models.DateField(db_index=True)),
                ('Symbol', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('Symbol_id', models.IntegerField(db_index=True, null=True)),
            ],
            options={
                'ordering': ['Date'],
            },
        ),
    ]
