# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='Close',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='Date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='Symbol',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
