# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0002_auto_20170508_1925'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockprice',
            name='dataapp_sto_Date_b020be_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockprice',
            name='dataapp_sto_Symbol_e0dc30_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockprice',
            name='dataapp_sto_Symbol__a3fac5_idx',
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['Date'], name='Date_idx'),
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['Symbol'], name='Symbol_idx'),
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['Symbol_id'], name='Symbol_id_idx'),
        ),
    ]
