# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0003_auto_20170508_2119'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockprice',
            name='Date_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockprice',
            name='Symbol_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockprice',
            name='Symbol_id_idx',
        ),
        migrations.AlterIndexTogether(
            name='stockprice',
            index_together=set([('Date', 'Symbol_id'), ('Date', 'Symbol'), ('Date', 'Symbol', 'Symbol_id')]),
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['Date'], name='dataapp_sto_Date_b020be_idx'),
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['Symbol'], name='dataapp_sto_Symbol_e0dc30_idx'),
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['Symbol_id'], name='dataapp_sto_Symbol__a3fac5_idx'),
        ),
    ]
