# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0004_auto_20170508_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockprice',
            options={},
        ),
    ]
