# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0005_auto_20170508_2237'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockprice',
            name='dataapp_sto_Date_1b3958_idx',
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='Symbol',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['Date', 'Symbol_id'], name='dataapp_sto_Date_d01d1e_idx'),
        ),
    ]
