# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-09 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0008_tradingdates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingdates',
            name='SymbolUsed',
        ),
    ]
